# Generated by Django 4.2.2 on 2023-06-22 21:06

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifiedOn', models.DateTimeField(default=datetime.datetime(2023, 6, 23, 2, 36, 42, 32830))),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(default='bangalore', max_length=100)),
                ('state', models.CharField(default='karnataka', max_length=50)),
                ('postal_code', models.IntegerField(default=560045)),
                ('country', models.CharField(default='india', max_length=100)),
                ('principal_name', models.CharField(max_length=100)),
                ('principal_email', models.CharField(max_length=100)),
                ('principal_phone', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(null=True, upload_to='database/images')),
                ('motto', models.TextField()),
                ('mission_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('office_location', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specialization_area', models.CharField(max_length=100)),
                ('budget_allocation', models.BigIntegerField(null=True)),
                ('facilities_available', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('research_areas', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('hod_name', models.CharField(max_length=100)),
                ('hod_email', models.CharField(max_length=100)),
                ('hod_phone', models.CharField(max_length=10)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.institution')),
            ],
        ),
    ]
